name = "PolaronQMC"
uuid = "ea65e02c-02a1-4f91-acc1-0c78ab1071d7"
authors = ["Jarvist Moore Frost <jarvist@gmail.com>", "Bradley Andrew Alan Martin <bam116@ic.ac.uk>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
